service: aws-node-rest-api-typescript

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  create:
    handler: app/handler.create
    events:
      - http:
          path: competitors
          method: post
           cors:
            origin: 'https://81dh31fa18.execute-api.us-east-1.amazonaws.com'
            headers:
              - MY_CUSTOM_HEADER
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
  update:
    handler: app/handler.update
    events:
      - http:
          path: competitors/{id}
          method: put
  find:
    handler: app/handler.find
    events:
      - http:
          path: competitors
          method: get
  findOne:
    handler: app/handler.findOne
    events:
      - http:
          path: competitors/{id}
          method: get

  deleteOne:
    handler: app/handler.deleteOne
    events:
      - http:
          path: competitors/{id}
          method: delete
