name: Deploy Lambda

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        args: -c "cd ./backend"
        node-version: ${{ matrix.node-version }}

    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: -c "cd ./backend && npm i && serverless deploy"
        entrypoint: /bin/bash
      env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: AKIAQYLDII4MEANBU473
        AWS_SECRET_ACCESS_KEY: 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